include: package:flutter_lints/flutter.yaml

analyzer:

linter:
  rules:
    - prefer_single_quotes
    - prefer_final_locals
    - always_declare_return_types
    - always_use_package_imports
    - prefer_final_fields